# How-to build & run locally
# Build: docker build -t prunplanner-frontend:latest .
# Run: docker run -p 80:80 prunplanner-frontend:latest --brotli --port 80


# --- BUILD STAGE ---
FROM node:22-alpine AS build
WORKDIR /app

# Enable pnpm
RUN corepack enable

# Pass build-time env variables
ARG VITE_APP_VERSION
ARG VITE_API_BASE_URL
ARG VITE_SHARE_BASE_URL
ARG VITE_GAME_DATA_STALE_MINUTES_BUILDINGS
ARG VITE_GAME_DATA_STALE_MINUTES_RECIPES
ARG VITE_GAME_DATA_STALE_MINUTES_MATERIALS
ARG VITE_GAME_DATA_STALE_MINUTES_EXCHANGES
ARG VITE_GAME_DATA_STALE_MINUTES_PLANETS

ENV VITE_APP_VERSION=$VITE_APP_VERSION \
    VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_SHARE_BASE_URL=$VITE_SHARE_BASE_URL \
    VITE_GAME_DATA_STALE_MINUTES_BUILDINGS=$VITE_GAME_DATA_STALE_MINUTES_BUILDINGS \
    VITE_GAME_DATA_STALE_MINUTES_RECIPES=$VITE_GAME_DATA_STALE_MINUTES_RECIPES \
    VITE_GAME_DATA_STALE_MINUTES_MATERIALS=$VITE_GAME_DATA_STALE_MINUTES_MATERIALS \
    VITE_GAME_DATA_STALE_MINUTES_EXCHANGES=$VITE_GAME_DATA_STALE_MINUTES_EXCHANGES \
    VITE_GAME_DATA_STALE_MINUTES_PLANETS=$VITE_GAME_DATA_STALE_MINUTES_PLANETS

# Copy package manager files
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy
COPY . .

# Build
RUN pnpm run build

# --- PRODUCTION STAGE ---
FROM devforth/spa-to-http:1.0.4 AS production
COPY --from=build /app/dist/ .
